/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.Sets
 *  net.fabricmc.api.EnvType
 *  net.fabricmc.api.Environment
 */
package net.minecraft.client.render.entity.model;

import com.google.common.collect.Sets;
import java.util.Set;
import java.util.stream.Stream;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.WoodType;
import net.minecraft.client.render.block.entity.HangingSignBlockEntityRenderer;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.client.render.entity.model.EquipmentModelData;
import net.minecraft.util.Identifier;

/*
 * Duplicate member names - consider using --renamedupmembers true
 */
@Environment(value=EnvType.CLIENT)
public class EntityModelLayers {
    private static final String MAIN = "main";
    private static final Set<EntityModelLayer> LAYERS = Sets.newHashSet();
    public static final EntityModelLayer ACACIA_BOAT = EntityModelLayers.registerMain("boat/acacia");
    public static final EntityModelLayer ACACIA_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/acacia");
    public static final EntityModelLayer ALLAY = EntityModelLayers.registerMain("allay");
    public static final EntityModelLayer ARMADILLO = EntityModelLayers.registerMain("armadillo");
    public static final EntityModelLayer ARMADILLO_BABY = EntityModelLayers.registerMain("armadillo_baby");
    public static final EntityModelLayer ARMOR_STAND = EntityModelLayers.registerMain("armor_stand");
    public static final EquipmentModelData<EntityModelLayer> ARMOR_STAND_EQUIPMENT = EntityModelLayers.registerEquipment("armor_stand");
    public static final EntityModelLayer ARMOR_STAND_SMALL = EntityModelLayers.registerMain("armor_stand_small");
    public static final EquipmentModelData<EntityModelLayer> SMALL_ARMOR_STAND_EQUIPMENT = EntityModelLayers.registerEquipment("armor_stand_small");
    public static final EntityModelLayer ARROW = EntityModelLayers.registerMain("arrow");
    public static final EntityModelLayer AXOLOTL = EntityModelLayers.registerMain("axolotl");
    public static final EntityModelLayer AXOLOTL_BABY = EntityModelLayers.registerMain("axolotl_baby");
    public static final EntityModelLayer BAMBOO_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/bamboo");
    public static final EntityModelLayer BAMBOO_BOAT = EntityModelLayers.registerMain("boat/bamboo");
    public static final EntityModelLayer STANDING_BANNER = EntityModelLayers.registerMain("standing_banner");
    public static final EntityModelLayer STANDING_BANNER_FLAG = EntityModelLayers.register("standing_banner", "flag");
    public static final EntityModelLayer WALL_BANNER = EntityModelLayers.registerMain("wall_banner");
    public static final EntityModelLayer WALL_BANNER_FLAG = EntityModelLayers.register("wall_banner", "flag");
    public static final EntityModelLayer BAT = EntityModelLayers.registerMain("bat");
    public static final EntityModelLayer BED_FOOT = EntityModelLayers.registerMain("bed_foot");
    public static final EntityModelLayer BED_HEAD = EntityModelLayers.registerMain("bed_head");
    public static final EntityModelLayer BEE = EntityModelLayers.registerMain("bee");
    public static final EntityModelLayer BEE_BABY = EntityModelLayers.registerMain("bee_baby");
    public static final EntityModelLayer BEE_STINGER = EntityModelLayers.registerMain("bee_stinger");
    public static final EntityModelLayer BELL = EntityModelLayers.registerMain("bell");
    public static final EntityModelLayer BIRCH_BOAT = EntityModelLayers.registerMain("boat/birch");
    public static final EntityModelLayer BIRCH_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/birch");
    public static final EntityModelLayer BLAZE = EntityModelLayers.registerMain("blaze");
    public static final EntityModelLayer BOAT = EntityModelLayers.register("boat", "water_patch");
    public static final EntityModelLayer BOGGED = EntityModelLayers.registerMain("bogged");
    public static final EquipmentModelData<EntityModelLayer> BOGGED_EQUIPMENT = EntityModelLayers.registerEquipment("bogged");
    public static final EntityModelLayer BOGGED_OUTER = EntityModelLayers.register("bogged", "outer");
    public static final EntityModelLayer BOOK = EntityModelLayers.registerMain("book");
    public static final EntityModelLayer BREEZE = EntityModelLayers.registerMain("breeze");
    public static final EntityModelLayer BREEZE_WIND = EntityModelLayers.register("breeze", "wind");
    public static final EntityModelLayer BREEZE_EYES = EntityModelLayers.register("breeze", "eyes");
    public static final EntityModelLayer CAMEL = EntityModelLayers.registerMain("camel");
    public static final EntityModelLayer CAMEL_BABY = EntityModelLayers.registerMain("camel_baby");
    public static final EntityModelLayer CAMEL_SADDLE = EntityModelLayers.register("camel", "saddle");
    public static final EntityModelLayer CAMEL_BABY_SADDLE = EntityModelLayers.register("camel_baby", "saddle");
    public static final EntityModelLayer CAMEL_HUSK = EntityModelLayers.register("camel_husk", "saddle");
    public static final EntityModelLayer CAMEL_HUSK_BABY = EntityModelLayers.register("camel_husk_baby", "saddle");
    public static final EntityModelLayer CAT = EntityModelLayers.registerMain("cat");
    public static final EntityModelLayer CAT_BABY = EntityModelLayers.registerMain("cat_baby");
    public static final EntityModelLayer CAT_BABY_COLLAR = EntityModelLayers.register("cat_baby", "collar");
    public static final EntityModelLayer CAT_COLLAR = EntityModelLayers.register("cat", "collar");
    public static final EntityModelLayer CAVE_SPIDER = EntityModelLayers.registerMain("cave_spider");
    public static final EntityModelLayer CHERRY_BOAT = EntityModelLayers.registerMain("boat/cherry");
    public static final EntityModelLayer CHERRY_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/cherry");
    public static final EntityModelLayer CHEST = EntityModelLayers.registerMain("chest");
    public static final EntityModelLayer CHEST_MINECART = EntityModelLayers.registerMain("chest_minecart");
    public static final EntityModelLayer CHICKEN = EntityModelLayers.registerMain("chicken");
    public static final EntityModelLayer CHICKEN_BABY = EntityModelLayers.registerMain("chicken_baby");
    public static final EntityModelLayer COD = EntityModelLayers.registerMain("cod");
    public static final EntityModelLayer COLD_CHICKEN = EntityModelLayers.registerMain("cold_chicken");
    public static final EntityModelLayer COLD_CHICKEN_BABY = EntityModelLayers.registerMain("cold_chicken_baby");
    public static final EntityModelLayer COLD_COW = EntityModelLayers.registerMain("cold_cow");
    public static final EntityModelLayer COLD_COW_BABY = EntityModelLayers.registerMain("cold_cow_baby");
    public static final EntityModelLayer COLD_PIG = EntityModelLayers.registerMain("cold_pig");
    public static final EntityModelLayer COLD_PIG_BABY = EntityModelLayers.registerMain("cold_pig_baby");
    public static final EntityModelLayer COMMAND_BLOCK_MINECART = EntityModelLayers.registerMain("command_block_minecart");
    public static final EntityModelLayer CONDUIT = EntityModelLayers.register("conduit", "cage");
    public static final EntityModelLayer CONDUIT_EYE = EntityModelLayers.register("conduit", "eye");
    public static final EntityModelLayer CONDUIT_SHELL = EntityModelLayers.register("conduit", "shell");
    public static final EntityModelLayer CONDUIT_WIND = EntityModelLayers.register("conduit", "wind");
    public static final EntityModelLayer COPPER_GOLEM = EntityModelLayers.registerMain("copper_golem");
    public static final EntityModelLayer COPPER_GOLEM_EYES = EntityModelLayers.register("copper_golem", "eyes");
    public static final EntityModelLayer COPPER_GOLEM_RUNNING = EntityModelLayers.registerMain("copper_golem_running");
    public static final EntityModelLayer COPPER_GOLEM_SITTING = EntityModelLayers.registerMain("copper_golem_sitting");
    public static final EntityModelLayer COPPER_GOLEM_STAR = EntityModelLayers.registerMain("copper_golem_star");
    public static final EntityModelLayer ZOMBIE_NAUTILUS_CORAL = EntityModelLayers.registerMain("zombie_nautilus_coral");
    public static final EntityModelLayer COW = EntityModelLayers.registerMain("cow");
    public static final EntityModelLayer COW_BABY = EntityModelLayers.registerMain("cow_baby");
    public static final EntityModelLayer CREAKING = EntityModelLayers.registerMain("creaking");
    public static final EntityModelLayer CREAKING_EYES = EntityModelLayers.register("creaking", "eyes");
    public static final EntityModelLayer CREEPER = EntityModelLayers.registerMain("creeper");
    public static final EntityModelLayer CREEPER_ARMOR = EntityModelLayers.register("creeper", "armor");
    public static final EntityModelLayer CREEPER_HEAD = EntityModelLayers.registerMain("creeper_head");
    public static final EntityModelLayer DARK_OAK_BOAT = EntityModelLayers.registerMain("boat/dark_oak");
    public static final EntityModelLayer DARK_OAK_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/dark_oak");
    public static final EntityModelLayer DECORATED_POT_BASE = EntityModelLayers.registerMain("decorated_pot_base");
    public static final EntityModelLayer DECORATED_POT_SIDES = EntityModelLayers.registerMain("decorated_pot_sides");
    public static final EntityModelLayer DOLPHIN = EntityModelLayers.registerMain("dolphin");
    public static final EntityModelLayer DOLPHIN_BABY = EntityModelLayers.registerMain("dolphin_baby");
    public static final EntityModelLayer DONKEY = EntityModelLayers.registerMain("donkey");
    public static final EntityModelLayer DONKEY_BABY = EntityModelLayers.registerMain("donkey_baby");
    public static final EntityModelLayer DONKEY_SADDLE = EntityModelLayers.register("donkey", "saddle");
    public static final EntityModelLayer DONKEY_BABY_SADDLE = EntityModelLayers.register("donkey_baby", "saddle");
    public static final EntityModelLayer DOUBLE_CHEST_LEFT = EntityModelLayers.registerMain("double_chest_left");
    public static final EntityModelLayer DOUBLE_CHEST_RIGHT = EntityModelLayers.registerMain("double_chest_right");
    public static final EntityModelLayer DRAGON_SKULL = EntityModelLayers.registerMain("dragon_skull");
    public static final EntityModelLayer DROWNED = EntityModelLayers.registerMain("drowned");
    public static final EntityModelLayer DROWNED_BABY = EntityModelLayers.registerMain("drowned_baby");
    public static final EquipmentModelData<EntityModelLayer> DROWNED_BABY_EQUIPMENT = EntityModelLayers.registerEquipment("drowned_baby");
    public static final EntityModelLayer DROWNED_BABY_OUTER = EntityModelLayers.register("drowned_baby", "outer");
    public static final EquipmentModelData<EntityModelLayer> DROWNED_EQUIPMENT = EntityModelLayers.registerEquipment("drowned");
    public static final EntityModelLayer DROWNED_OUTER = EntityModelLayers.register("drowned", "outer");
    public static final EntityModelLayer ELDER_GUARDIAN = EntityModelLayers.registerMain("elder_guardian");
    public static final EntityModelLayer ELYTRA = EntityModelLayers.registerMain("elytra");
    public static final EntityModelLayer ELYTRA_BABY = EntityModelLayers.registerMain("elytra_baby");
    public static final EntityModelLayer ENDERMAN = EntityModelLayers.registerMain("enderman");
    public static final EntityModelLayer ENDERMITE = EntityModelLayers.registerMain("endermite");
    public static final EntityModelLayer ENDER_DRAGON = EntityModelLayers.registerMain("ender_dragon");
    public static final EntityModelLayer END_CRYSTAL = EntityModelLayers.registerMain("end_crystal");
    public static final EntityModelLayer EVOKER = EntityModelLayers.registerMain("evoker");
    public static final EntityModelLayer EVOKER_FANGS = EntityModelLayers.registerMain("evoker_fangs");
    public static final EntityModelLayer FOX = EntityModelLayers.registerMain("fox");
    public static final EntityModelLayer FOX_BABY = EntityModelLayers.registerMain("fox_baby");
    public static final EntityModelLayer FROG = EntityModelLayers.registerMain("frog");
    public static final EntityModelLayer FURNACE_MINECART = EntityModelLayers.registerMain("furnace_minecart");
    public static final EntityModelLayer GHAST = EntityModelLayers.registerMain("ghast");
    public static final EntityModelLayer GIANT = EntityModelLayers.registerMain("giant");
    public static final EquipmentModelData<EntityModelLayer> GIANT_EQUIPMENT = EntityModelLayers.registerEquipment("giant");
    public static final EntityModelLayer GLOW_SQUID = EntityModelLayers.registerMain("glow_squid");
    public static final EntityModelLayer GLOW_SQUID_BABY = EntityModelLayers.registerMain("glow_squid_baby");
    public static final EntityModelLayer GOAT = EntityModelLayers.registerMain("goat");
    public static final EntityModelLayer GOAT_BABY = EntityModelLayers.registerMain("goat_baby");
    public static final EntityModelLayer GUARDIAN = EntityModelLayers.registerMain("guardian");
    public static final EntityModelLayer HAPPY_GHAST = EntityModelLayers.registerMain("happy_ghast");
    public static final EntityModelLayer HAPPY_GHAST_BABY = EntityModelLayers.registerMain("happy_ghast_baby");
    public static final EntityModelLayer HAPPY_GHAST_HARNESS = EntityModelLayers.registerMain("happy_ghast_harness");
    public static final EntityModelLayer HAPPY_GHAST_BABY_HARNESS = EntityModelLayers.registerMain("happy_ghast_baby_harness");
    public static final EntityModelLayer HAPPY_GHAST_ROPES = EntityModelLayers.registerMain("happy_ghast_ropes");
    public static final EntityModelLayer HAPPY_GHAST_BABY_ROPES = EntityModelLayers.registerMain("happy_ghast_baby_ropes");
    public static final EntityModelLayer HOGLIN = EntityModelLayers.registerMain("hoglin");
    public static final EntityModelLayer HOGLIN_BABY = EntityModelLayers.registerMain("hoglin_baby");
    public static final EntityModelLayer HOPPER_MINECART = EntityModelLayers.registerMain("hopper_minecart");
    public static final EntityModelLayer HORSE = EntityModelLayers.registerMain("horse");
    public static final EntityModelLayer HORSE_ARMOR = EntityModelLayers.registerMain("horse_armor");
    public static final EntityModelLayer HORSE_SADDLE = EntityModelLayers.register("horse", "saddle");
    public static final EntityModelLayer HORSE_BABY = EntityModelLayers.registerMain("horse_baby");
    public static final EntityModelLayer HORSE_ARMOR_BABY = EntityModelLayers.registerMain("horse_armor_baby");
    public static final EntityModelLayer HORSE_BABY_SADDLE = EntityModelLayers.register("horse_baby", "saddle");
    public static final EntityModelLayer HUSK = EntityModelLayers.registerMain("husk");
    public static final EntityModelLayer HUSK_BABY = EntityModelLayers.registerMain("husk_baby");
    public static final EquipmentModelData<EntityModelLayer> HUSK_BABY_EQUIPMENT = EntityModelLayers.registerEquipment("husk_baby");
    public static final EquipmentModelData<EntityModelLayer> HUSK_EQUIPMENT = EntityModelLayers.registerEquipment("husk");
    public static final EntityModelLayer ILLUSIONER = EntityModelLayers.registerMain("illusioner");
    public static final EntityModelLayer IRON_GOLEM = EntityModelLayers.registerMain("iron_golem");
    public static final EntityModelLayer JUNGLE_BOAT = EntityModelLayers.registerMain("boat/jungle");
    public static final EntityModelLayer JUNGLE_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/jungle");
    public static final EntityModelLayer LEASH_KNOT = EntityModelLayers.registerMain("leash_knot");
    public static final EntityModelLayer LLAMA = EntityModelLayers.registerMain("llama");
    public static final EntityModelLayer LLAMA_BABY = EntityModelLayers.registerMain("llama_baby");
    public static final EntityModelLayer LLAMA_BABY_DECOR = EntityModelLayers.register("llama_baby", "decor");
    public static final EntityModelLayer LLAMA_DECOR = EntityModelLayers.register("llama", "decor");
    public static final EntityModelLayer LLAMA_SPIT = EntityModelLayers.registerMain("llama_spit");
    public static final EntityModelLayer MAGMA_CUBE = EntityModelLayers.registerMain("magma_cube");
    public static final EntityModelLayer MANGROVE_BOAT = EntityModelLayers.registerMain("boat/mangrove");
    public static final EntityModelLayer MANGROVE_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/mangrove");
    public static final EntityModelLayer MINECART = EntityModelLayers.registerMain("minecart");
    public static final EntityModelLayer MOOSHROOM = EntityModelLayers.registerMain("mooshroom");
    public static final EntityModelLayer MOOSHROOM_BABY = EntityModelLayers.registerMain("mooshroom_baby");
    public static final EntityModelLayer MULE = EntityModelLayers.registerMain("mule");
    public static final EntityModelLayer MULE_BABY = EntityModelLayers.registerMain("mule_baby");
    public static final EntityModelLayer MULE_SADDLE = EntityModelLayers.register("mule", "saddle");
    public static final EntityModelLayer MULE_BABY_SADDLE = EntityModelLayers.register("mule_baby", "saddle");
    public static final EntityModelLayer NAUTILUS = EntityModelLayers.registerMain("nautilus");
    public static final EntityModelLayer NAUTILUS_BABY = EntityModelLayers.registerMain("nautilus_baby");
    public static final EntityModelLayer NAUTILUS_SADDLE = EntityModelLayers.register("nautilus", "saddle");
    public static final EntityModelLayer NAUTILUS_ARMOR = EntityModelLayers.registerMain("nautilus_armor");
    public static final EntityModelLayer OAK_BOAT = EntityModelLayers.registerMain("boat/oak");
    public static final EntityModelLayer OAK_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/oak");
    public static final EntityModelLayer OCELOT = EntityModelLayers.registerMain("ocelot");
    public static final EntityModelLayer OCELOT_BABY = EntityModelLayers.registerMain("ocelot_baby");
    public static final EntityModelLayer PALE_OAK_BOAT = EntityModelLayers.registerMain("boat/pale_oak");
    public static final EntityModelLayer PALE_OAK_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/pale_oak");
    public static final EntityModelLayer PANDA = EntityModelLayers.registerMain("panda");
    public static final EntityModelLayer PANDA_BABY = EntityModelLayers.registerMain("panda_baby");
    public static final EntityModelLayer PARCHED = EntityModelLayers.registerMain("parched");
    public static final EquipmentModelData<EntityModelLayer> PARCHED_EQUIPMENT = EntityModelLayers.registerEquipment("parched");
    public static final EntityModelLayer PARCHED_OUTER = EntityModelLayers.register("parched", "outer");
    public static final EntityModelLayer PARROT = EntityModelLayers.registerMain("parrot");
    public static final EntityModelLayer PHANTOM = EntityModelLayers.registerMain("phantom");
    public static final EntityModelLayer PIG = EntityModelLayers.registerMain("pig");
    public static final EntityModelLayer PIGLIN = EntityModelLayers.registerMain("piglin");
    public static final EntityModelLayer PIGLIN_BABY = EntityModelLayers.registerMain("piglin_baby");
    public static final EquipmentModelData<EntityModelLayer> PIGLIN_BABY_EQUIPMENT = EntityModelLayers.registerEquipment("piglin_baby");
    public static final EntityModelLayer PIGLIN_BRUTE = EntityModelLayers.registerMain("piglin_brute");
    public static final EquipmentModelData<EntityModelLayer> PIGLIN_BRUTE_EQUIPMENT = EntityModelLayers.registerEquipment("piglin_brute");
    public static final EntityModelLayer PIGLIN_HEAD = EntityModelLayers.registerMain("piglin_head");
    public static final EquipmentModelData<EntityModelLayer> PIGLIN_EQUIPMENT = EntityModelLayers.registerEquipment("piglin");
    public static final EntityModelLayer PIG_BABY = EntityModelLayers.registerMain("pig_baby");
    public static final EntityModelLayer PIG_BABY_SADDLE = EntityModelLayers.register("pig_baby", "saddle");
    public static final EntityModelLayer PIG_SADDLE = EntityModelLayers.register("pig", "saddle");
    public static final EntityModelLayer PILLAGER = EntityModelLayers.registerMain("pillager");
    public static final EntityModelLayer PLAYER = EntityModelLayers.registerMain("player");
    public static final EntityModelLayer PLAYER_CAPE = EntityModelLayers.register("player", "cape");
    public static final EntityModelLayer PLAYER_EARS = EntityModelLayers.register("player", "ears");
    public static final EntityModelLayer PLAYER_HEAD = EntityModelLayers.registerMain("player_head");
    public static final EquipmentModelData<EntityModelLayer> PLAYER_EQUIPMENT = EntityModelLayers.registerEquipment("player");
    public static final EntityModelLayer PLAYER_SLIM = EntityModelLayers.registerMain("player_slim");
    public static final EquipmentModelData<EntityModelLayer> PLAYER_SLIM;
    public static final EntityModelLayer SPIN_ATTACK;
    public static final EntityModelLayer POLAR_BEAR;
    public static final EntityModelLayer POLAR_BEAR_BABY;
    public static final EntityModelLayer PUFFERFISH_BIG;
    public static final EntityModelLayer PUFFERFISH_MEDIUM;
    public static final EntityModelLayer PUFFERFISH_SMALL;
    public static final EntityModelLayer RABBIT;
    public static final EntityModelLayer RABBIT_BABY;
    public static final EntityModelLayer RAVAGER;
    public static final EntityModelLayer SALMON;
    public static final EntityModelLayer SALMON_LARGE;
    public static final EntityModelLayer SALMON_SMALL;
    public static final EntityModelLayer SHEEP;
    public static final EntityModelLayer SHEEP_BABY;
    public static final EntityModelLayer SHEEP_BABY_WOOL;
    public static final EntityModelLayer SHEEP_WOOL;
    public static final EntityModelLayer SHEEP_WOOL_UNDERCOAT;
    public static final EntityModelLayer SHEEP_BABY_WOOL_UNDERCOAT;
    public static final EntityModelLayer SHIELD;
    public static final EntityModelLayer SHULKER;
    public static final EntityModelLayer SHULKER_BOX;
    public static final EntityModelLayer SHULKER_BULLET;
    public static final EntityModelLayer SILVERFISH;
    public static final EntityModelLayer SKELETON;
    public static final EntityModelLayer SKELETON_HORSE;
    public static final EntityModelLayer SKELETON_HORSE_BABY;
    public static final EntityModelLayer SKELETON_HORSE_SADDLE;
    public static final EntityModelLayer SKELETON_HORSE_BABY_SADDLE;
    public static final EquipmentModelData<EntityModelLayer> SKELETON_EQUIPMENT;
    public static final EntityModelLayer SKELETON_SKULL;
    public static final EntityModelLayer SLIME;
    public static final EntityModelLayer SLIME_OUTER;
    public static final EntityModelLayer SNIFFER;
    public static final EntityModelLayer SNIFFER_BABY;
    public static final EntityModelLayer SNOW_GOLEM;
    public static final EntityModelLayer SPAWNER_MINECART;
    public static final EntityModelLayer SPIDER;
    public static final EntityModelLayer SPRUCE_BOAT;
    public static final EntityModelLayer SPRUCE_CHEST_BOAT;
    public static final EntityModelLayer SQUID;
    public static final EntityModelLayer SQUID_BABY;
    public static final EntityModelLayer STRAY;
    public static final EquipmentModelData<EntityModelLayer> STRAY_EQUIPMENT;
    public static final EntityModelLayer STRAY_OUTER;
    public static final EntityModelLayer STRIDER;
    public static final EntityModelLayer STRIDER_SADDLE;
    public static final EntityModelLayer STRIDER_BABY;
    public static final EntityModelLayer STRIDER_BABY_SADDLE;
    public static final EntityModelLayer TADPOLE;
    public static final EntityModelLayer TNT_MINECART;
    public static final EntityModelLayer TRADER_LLAMA;
    public static final EntityModelLayer TRADER_LLAMA_BABY;
    public static final EntityModelLayer TRIDENT;
    public static final EntityModelLayer TROPICAL_FISH_LARGE;
    public static final EntityModelLayer TROPICAL_FISH_LARGE_PATTERN;
    public static final EntityModelLayer TROPICAL_FISH_SMALL;
    public static final EntityModelLayer TROPICAL_FISH_SMALL_PATTERN;
    public static final EntityModelLayer TURTLE;
    public static final EntityModelLayer TURTLE_BABY;
    public static final EntityModelLayer UNDEAD_HORSE_ARMOR;
    public static final EntityModelLayer UNDEAD_HORSE_BABY_ARMOR;
    public static final EntityModelLayer VEX;
    public static final EntityModelLayer VILLAGER;
    public static final EntityModelLayer VILLAGER_NO_HAT;
    public static final EntityModelLayer VILLAGER_BABY;
    public static final EntityModelLayer VILLAGER_BABY_NO_HAT;
    public static final EntityModelLayer VINDICATOR;
    public static final EntityModelLayer WANDERING_TRADER;
    public static final EntityModelLayer WARDEN;
    public static final EntityModelLayer WARDEN_BIOLUMINESCENT;
    public static final EntityModelLayer WARDEN_PULSATING_SPOTS;
    public static final EntityModelLayer WARDEN_TENDRILS;
    public static final EntityModelLayer WARDEN_HEART;
    public static final EntityModelLayer WARM_COW;
    public static final EntityModelLayer WARM_COW_BABY;
    public static final EntityModelLayer WIND_CHARGE;
    public static final EntityModelLayer WITCH;
    public static final EntityModelLayer WITHER;
    public static final EntityModelLayer WITHER_ARMOR;
    public static final EntityModelLayer WITHER_SKELETON;
    public static final EquipmentModelData<EntityModelLayer> WITHER_SKELETON_EQUIPMENT;
    public static final EntityModelLayer WITHER_SKELETON_SKULL;
    public static final EntityModelLayer WITHER_SKULL;
    public static final EntityModelLayer WOLF;
    public static final EntityModelLayer WOLF_ARMOR;
    public static final EntityModelLayer WOLF_BABY;
    public static final EntityModelLayer WOLF_BABY_ARMOR;
    public static final EntityModelLayer ZOGLIN;
    public static final EntityModelLayer ZOGLIN_BABY;
    public static final EntityModelLayer ZOMBIE;
    public static final EntityModelLayer ZOMBIE_BABY;
    public static final EquipmentModelData<EntityModelLayer> ZOMBIE_BABY_EQUIPMENT;
    public static final EntityModelLayer ZOMBIE_HEAD;
    public static final EntityModelLayer ZOMBIE_HORSE;
    public static final EntityModelLayer ZOMBIE_HORSE_BABY;
    public static final EntityModelLayer ZOMBIE_HORSE_SADDLE;
    public static final EntityModelLayer ZOMBIE_HORSE_BABY_SADDLE;
    public static final EquipmentModelData<EntityModelLayer> ZOMBIE_EQUIPMENT;
    public static final EntityModelLayer ZOMBIE_VILLAGER;
    public static final EntityModelLayer ZOMBIE_VILLAGER_NO_HAT;
    public static final EntityModelLayer ZOMBIE_VILLAGER_BABY;
    public static final EntityModelLayer ZOMBIE_VILLAGER_BABY_NO_HAT;
    public static final EquipmentModelData<EntityModelLayer> ZOMBIE_VILLAGER_BABY_EQUIPMENT;
    public static final EquipmentModelData<EntityModelLayer> ZOMBIE_VILLAGER_EQUIPMENT;
    public static final EntityModelLayer ZOMBIFIED_PIGLIN;
    public static final EntityModelLayer ZOMBIFIED_PIGLIN_BABY;
    public static final EquipmentModelData<EntityModelLayer> ZOMBIFIED_PIGLIN_BABY_EQUIPMENT;
    public static final EquipmentModelData<EntityModelLayer> ZOMBIFIED_PIGLIN_EQUIPMENT;
    public static final EntityModelLayer ZOMBIE_NAUTILUS;

    private static EntityModelLayer registerMain(String id) {
        return EntityModelLayers.register(id, MAIN);
    }

    private static EntityModelLayer register(String id, String layer) {
        EntityModelLayer entityModelLayer = EntityModelLayers.create(id, layer);
        if (!LAYERS.add(entityModelLayer)) {
            throw new IllegalStateException("Duplicate registration for " + String.valueOf(entityModelLayer));
        }
        return entityModelLayer;
    }

    private static EntityModelLayer create(String id, String layer) {
        return new EntityModelLayer(Identifier.ofVanilla(id), layer);
    }

    private static EquipmentModelData<EntityModelLayer> registerEquipment(String id) {
        return new EquipmentModelData<EntityModelLayer>(EntityModelLayers.register(id, "helmet"), EntityModelLayers.register(id, "chestplate"), EntityModelLayers.register(id, "leggings"), EntityModelLayers.register(id, "boots"));
    }

    public static EntityModelLayer createStandingSign(WoodType type) {
        return EntityModelLayers.create("sign/standing/" + type.name(), MAIN);
    }

    public static EntityModelLayer createWallSign(WoodType type) {
        return EntityModelLayers.create("sign/wall/" + type.name(), MAIN);
    }

    public static EntityModelLayer createHangingSign(WoodType type, HangingSignBlockEntityRenderer.AttachmentType attachmentType) {
        return EntityModelLayers.create("hanging_sign/" + type.name() + "/" + attachmentType.asString(), MAIN);
    }

    public static Stream<EntityModelLayer> getLayers() {
        return LAYERS.stream();
    }

    static {
        PLAYER_SLIM = EntityModelLayers.registerEquipment("player_slim");
        SPIN_ATTACK = EntityModelLayers.registerMain("spin_attack");
        POLAR_BEAR = EntityModelLayers.registerMain("polar_bear");
        POLAR_BEAR_BABY = EntityModelLayers.registerMain("polar_bear_baby");
        PUFFERFISH_BIG = EntityModelLayers.registerMain("pufferfish_big");
        PUFFERFISH_MEDIUM = EntityModelLayers.registerMain("pufferfish_medium");
        PUFFERFISH_SMALL = EntityModelLayers.registerMain("pufferfish_small");
        RABBIT = EntityModelLayers.registerMain("rabbit");
        RABBIT_BABY = EntityModelLayers.registerMain("rabbit_baby");
        RAVAGER = EntityModelLayers.registerMain("ravager");
        SALMON = EntityModelLayers.registerMain("salmon");
        SALMON_LARGE = EntityModelLayers.registerMain("salmon_large");
        SALMON_SMALL = EntityModelLayers.registerMain("salmon_small");
        SHEEP = EntityModelLayers.registerMain("sheep");
        SHEEP_BABY = EntityModelLayers.registerMain("sheep_baby");
        SHEEP_BABY_WOOL = EntityModelLayers.register("sheep_baby", "wool");
        SHEEP_WOOL = EntityModelLayers.register("sheep", "wool");
        SHEEP_WOOL_UNDERCOAT = EntityModelLayers.register("sheep", "wool_undercoat");
        SHEEP_BABY_WOOL_UNDERCOAT = EntityModelLayers.register("sheep_baby", "wool_undercoat");
        SHIELD = EntityModelLayers.registerMain("shield");
        SHULKER = EntityModelLayers.registerMain("shulker");
        SHULKER_BOX = EntityModelLayers.registerMain("shulker_box");
        SHULKER_BULLET = EntityModelLayers.registerMain("shulker_bullet");
        SILVERFISH = EntityModelLayers.registerMain("silverfish");
        SKELETON = EntityModelLayers.registerMain("skeleton");
        SKELETON_HORSE = EntityModelLayers.registerMain("skeleton_horse");
        SKELETON_HORSE_BABY = EntityModelLayers.registerMain("skeleton_horse_baby");
        SKELETON_HORSE_SADDLE = EntityModelLayers.register("skeleton_horse", "saddle");
        SKELETON_HORSE_BABY_SADDLE = EntityModelLayers.register("skeleton_horse_baby", "saddle");
        SKELETON_EQUIPMENT = EntityModelLayers.registerEquipment("skeleton");
        SKELETON_SKULL = EntityModelLayers.registerMain("skeleton_skull");
        SLIME = EntityModelLayers.registerMain("slime");
        SLIME_OUTER = EntityModelLayers.register("slime", "outer");
        SNIFFER = EntityModelLayers.registerMain("sniffer");
        SNIFFER_BABY = EntityModelLayers.registerMain("sniffer_baby");
        SNOW_GOLEM = EntityModelLayers.registerMain("snow_golem");
        SPAWNER_MINECART = EntityModelLayers.registerMain("spawner_minecart");
        SPIDER = EntityModelLayers.registerMain("spider");
        SPRUCE_BOAT = EntityModelLayers.registerMain("boat/spruce");
        SPRUCE_CHEST_BOAT = EntityModelLayers.registerMain("chest_boat/spruce");
        SQUID = EntityModelLayers.registerMain("squid");
        SQUID_BABY = EntityModelLayers.registerMain("squid_baby");
        STRAY = EntityModelLayers.registerMain("stray");
        STRAY_EQUIPMENT = EntityModelLayers.registerEquipment("stray");
        STRAY_OUTER = EntityModelLayers.register("stray", "outer");
        STRIDER = EntityModelLayers.registerMain("strider");
        STRIDER_SADDLE = EntityModelLayers.register("strider", "saddle");
        STRIDER_BABY = EntityModelLayers.registerMain("strider_baby");
        STRIDER_BABY_SADDLE = EntityModelLayers.register("strider_baby", "saddle");
        TADPOLE = EntityModelLayers.registerMain("tadpole");
        TNT_MINECART = EntityModelLayers.registerMain("tnt_minecart");
        TRADER_LLAMA = EntityModelLayers.registerMain("trader_llama");
        TRADER_LLAMA_BABY = EntityModelLayers.registerMain("trader_llama_baby");
        TRIDENT = EntityModelLayers.registerMain("trident");
        TROPICAL_FISH_LARGE = EntityModelLayers.registerMain("tropical_fish_large");
        TROPICAL_FISH_LARGE_PATTERN = EntityModelLayers.register("tropical_fish_large", "pattern");
        TROPICAL_FISH_SMALL = EntityModelLayers.registerMain("tropical_fish_small");
        TROPICAL_FISH_SMALL_PATTERN = EntityModelLayers.register("tropical_fish_small", "pattern");
        TURTLE = EntityModelLayers.registerMain("turtle");
        TURTLE_BABY = EntityModelLayers.registerMain("turtle_baby");
        UNDEAD_HORSE_ARMOR = EntityModelLayers.registerMain("undead_horse_armor");
        UNDEAD_HORSE_BABY_ARMOR = EntityModelLayers.registerMain("undead_horse_baby_armor");
        VEX = EntityModelLayers.registerMain("vex");
        VILLAGER = EntityModelLayers.registerMain("villager");
        VILLAGER_NO_HAT = EntityModelLayers.registerMain("villager_no_hat");
        VILLAGER_BABY = EntityModelLayers.registerMain("villager_baby");
        VILLAGER_BABY_NO_HAT = EntityModelLayers.registerMain("villager_baby_no_hat");
        VINDICATOR = EntityModelLayers.registerMain("vindicator");
        WANDERING_TRADER = EntityModelLayers.registerMain("wandering_trader");
        WARDEN = EntityModelLayers.registerMain("warden");
        WARDEN_BIOLUMINESCENT = EntityModelLayers.register("warden", "bioluminescent");
        WARDEN_PULSATING_SPOTS = EntityModelLayers.register("warden", "pulsating_spots");
        WARDEN_TENDRILS = EntityModelLayers.register("warden", "tendrils");
        WARDEN_HEART = EntityModelLayers.register("warden", "heart");
        WARM_COW = EntityModelLayers.registerMain("warm_cow");
        WARM_COW_BABY = EntityModelLayers.registerMain("warm_cow_baby");
        WIND_CHARGE = EntityModelLayers.registerMain("wind_charge");
        WITCH = EntityModelLayers.registerMain("witch");
        WITHER = EntityModelLayers.registerMain("wither");
        WITHER_ARMOR = EntityModelLayers.register("wither", "armor");
        WITHER_SKELETON = EntityModelLayers.registerMain("wither_skeleton");
        WITHER_SKELETON_EQUIPMENT = EntityModelLayers.registerEquipment("wither_skeleton");
        WITHER_SKELETON_SKULL = EntityModelLayers.registerMain("wither_skeleton_skull");
        WITHER_SKULL = EntityModelLayers.registerMain("wither_skull");
        WOLF = EntityModelLayers.registerMain("wolf");
        WOLF_ARMOR = EntityModelLayers.registerMain("wolf_armor");
        WOLF_BABY = EntityModelLayers.registerMain("wolf_baby");
        WOLF_BABY_ARMOR = EntityModelLayers.registerMain("wolf_baby_armor");
        ZOGLIN = EntityModelLayers.registerMain("zoglin");
        ZOGLIN_BABY = EntityModelLayers.registerMain("zoglin_baby");
        ZOMBIE = EntityModelLayers.registerMain("zombie");
        ZOMBIE_BABY = EntityModelLayers.registerMain("zombie_baby");
        ZOMBIE_BABY_EQUIPMENT = EntityModelLayers.registerEquipment("zombie_baby");
        ZOMBIE_HEAD = EntityModelLayers.registerMain("zombie_head");
        ZOMBIE_HORSE = EntityModelLayers.registerMain("zombie_horse");
        ZOMBIE_HORSE_BABY = EntityModelLayers.registerMain("zombie_horse_baby");
        ZOMBIE_HORSE_SADDLE = EntityModelLayers.register("zombie_horse", "saddle");
        ZOMBIE_HORSE_BABY_SADDLE = EntityModelLayers.register("zombie_horse_baby", "saddle");
        ZOMBIE_EQUIPMENT = EntityModelLayers.registerEquipment("zombie");
        ZOMBIE_VILLAGER = EntityModelLayers.registerMain("zombie_villager");
        ZOMBIE_VILLAGER_NO_HAT = EntityModelLayers.registerMain("zombie_villager_no_hat");
        ZOMBIE_VILLAGER_BABY = EntityModelLayers.registerMain("zombie_villager_baby");
        ZOMBIE_VILLAGER_BABY_NO_HAT = EntityModelLayers.registerMain("zombie_villager_baby_no_hat");
        ZOMBIE_VILLAGER_BABY_EQUIPMENT = EntityModelLayers.registerEquipment("zombie_villager_baby");
        ZOMBIE_VILLAGER_EQUIPMENT = EntityModelLayers.registerEquipment("zombie_villager");
        ZOMBIFIED_PIGLIN = EntityModelLayers.registerMain("zombified_piglin");
        ZOMBIFIED_PIGLIN_BABY = EntityModelLayers.registerMain("zombified_piglin_baby");
        ZOMBIFIED_PIGLIN_BABY_EQUIPMENT = EntityModelLayers.registerEquipment("zombified_piglin_baby");
        ZOMBIFIED_PIGLIN_EQUIPMENT = EntityModelLayers.registerEquipment("zombified_piglin");
        ZOMBIE_NAUTILUS = EntityModelLayers.registerMain("zombie_nautilus");
    }
}
