/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.fabricmc.api.EnvType
 *  net.fabricmc.api.Environment
 */
package net.minecraft.client.render.block;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.render.block.BlockModelRenderer;
import net.minecraft.util.Util;
import net.minecraft.util.math.Direction;

@Environment(value=EnvType.CLIENT)
protected static final class BlockModelRenderer.NeighborData
extends Enum<BlockModelRenderer.NeighborData> {
    public static final /* enum */ BlockModelRenderer.NeighborData DOWN = new BlockModelRenderer.NeighborData(new Direction[]{Direction.WEST, Direction.EAST, Direction.NORTH, Direction.SOUTH}, 0.5f, true, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.SOUTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.SOUTH});
    public static final /* enum */ BlockModelRenderer.NeighborData UP = new BlockModelRenderer.NeighborData(new Direction[]{Direction.EAST, Direction.WEST, Direction.NORTH, Direction.SOUTH}, 1.0f, true, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.SOUTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.SOUTH});
    public static final /* enum */ BlockModelRenderer.NeighborData NORTH = new BlockModelRenderer.NeighborData(new Direction[]{Direction.UP, Direction.DOWN, Direction.EAST, Direction.WEST}, 0.8f, true, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_WEST}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_EAST}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_EAST}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_WEST});
    public static final /* enum */ BlockModelRenderer.NeighborData SOUTH = new BlockModelRenderer.NeighborData(new Direction[]{Direction.WEST, Direction.EAST, Direction.DOWN, Direction.UP}, 0.8f, true, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.WEST}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_WEST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.WEST, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.WEST}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.EAST}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_EAST, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.EAST, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.EAST});
    public static final /* enum */ BlockModelRenderer.NeighborData WEST = new BlockModelRenderer.NeighborData(new Direction[]{Direction.UP, Direction.DOWN, Direction.NORTH, Direction.SOUTH}, 0.6f, true, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.SOUTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.SOUTH});
    public static final /* enum */ BlockModelRenderer.NeighborData EAST = new BlockModelRenderer.NeighborData(new Direction[]{Direction.DOWN, Direction.UP, Direction.NORTH, Direction.SOUTH}, 0.6f, true, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.SOUTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.FLIP_DOWN, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.DOWN, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.NORTH, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_NORTH, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.NORTH}, new BlockModelRenderer.NeighborOrientation[]{BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.SOUTH, BlockModelRenderer.NeighborOrientation.FLIP_UP, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.FLIP_SOUTH, BlockModelRenderer.NeighborOrientation.UP, BlockModelRenderer.NeighborOrientation.SOUTH});
    final Direction[] faces;
    final boolean nonCubicWeight;
    final BlockModelRenderer.NeighborOrientation[] field_4192;
    final BlockModelRenderer.NeighborOrientation[] field_4185;
    final BlockModelRenderer.NeighborOrientation[] field_4180;
    final BlockModelRenderer.NeighborOrientation[] field_4188;
    private static final BlockModelRenderer.NeighborData[] VALUES;
    private static final /* synthetic */ BlockModelRenderer.NeighborData[] field_4193;

    public static BlockModelRenderer.NeighborData[] values() {
        return (BlockModelRenderer.NeighborData[])field_4193.clone();
    }

    public static BlockModelRenderer.NeighborData valueOf(String string) {
        return Enum.valueOf(BlockModelRenderer.NeighborData.class, string);
    }

    private BlockModelRenderer.NeighborData(Direction[] faces, float f, boolean nonCubicWeight, BlockModelRenderer.NeighborOrientation[] neighborOrientations, BlockModelRenderer.NeighborOrientation[] neighborOrientations2, BlockModelRenderer.NeighborOrientation[] neighborOrientations3, BlockModelRenderer.NeighborOrientation[] neighborOrientations4) {
        this.faces = faces;
        this.nonCubicWeight = nonCubicWeight;
        this.field_4192 = neighborOrientations;
        this.field_4185 = neighborOrientations2;
        this.field_4180 = neighborOrientations3;
        this.field_4188 = neighborOrientations4;
    }

    public static BlockModelRenderer.NeighborData getData(Direction direction) {
        return VALUES[direction.getIndex()];
    }

    private static /* synthetic */ BlockModelRenderer.NeighborData[] method_36917() {
        return new BlockModelRenderer.NeighborData[]{DOWN, UP, NORTH, SOUTH, WEST, EAST};
    }

    static {
        field_4193 = BlockModelRenderer.NeighborData.method_36917();
        VALUES = Util.make(new BlockModelRenderer.NeighborData[6], values -> {
            values[Direction.DOWN.getIndex()] = DOWN;
            values[Direction.UP.getIndex()] = UP;
            values[Direction.NORTH.getIndex()] = NORTH;
            values[Direction.SOUTH.getIndex()] = SOUTH;
            values[Direction.WEST.getIndex()] = WEST;
            values[Direction.EAST.getIndex()] = EAST;
        });
    }
}
