package net.minecraft.loot;

import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.DyeColor;
import net.minecraft.util.Identifier;
import net.minecraft.util.Util;

public class LootTables {
   private static final Set LOOT_TABLES = new HashSet();
   private static final Set LOOT_TABLES_READ_ONLY;
   public static final RegistryKey SPAWN_BONUS_CHEST;
   public static final RegistryKey END_CITY_TREASURE_CHEST;
   public static final RegistryKey SIMPLE_DUNGEON_CHEST;
   public static final RegistryKey VILLAGE_WEAPONSMITH_CHEST;
   public static final RegistryKey VILLAGE_TOOLSMITH_CHEST;
   public static final RegistryKey VILLAGE_ARMORER_CHEST;
   public static final RegistryKey VILLAGE_CARTOGRAPHER_CHEST;
   public static final RegistryKey VILLAGE_MASON_CHEST;
   public static final RegistryKey VILLAGE_SHEPARD_CHEST;
   public static final RegistryKey VILLAGE_BUTCHER_CHEST;
   public static final RegistryKey VILLAGE_FLETCHER_CHEST;
   public static final RegistryKey VILLAGE_FISHER_CHEST;
   public static final RegistryKey VILLAGE_TANNERY_CHEST;
   public static final RegistryKey VILLAGE_TEMPLE_CHEST;
   public static final RegistryKey VILLAGE_DESERT_HOUSE_CHEST;
   public static final RegistryKey VILLAGE_PLAINS_CHEST;
   public static final RegistryKey VILLAGE_TAIGA_HOUSE_CHEST;
   public static final RegistryKey VILLAGE_SNOWY_HOUSE_CHEST;
   public static final RegistryKey VILLAGE_SAVANNA_HOUSE_CHEST;
   public static final RegistryKey ABANDONED_MINESHAFT_CHEST;
   public static final RegistryKey NETHER_BRIDGE_CHEST;
   public static final RegistryKey STRONGHOLD_LIBRARY_CHEST;
   public static final RegistryKey STRONGHOLD_CROSSING_CHEST;
   public static final RegistryKey STRONGHOLD_CORRIDOR_CHEST;
   public static final RegistryKey DESERT_PYRAMID_CHEST;
   public static final RegistryKey JUNGLE_TEMPLE_CHEST;
   public static final RegistryKey JUNGLE_TEMPLE_DISPENSER_CHEST;
   public static final RegistryKey IGLOO_CHEST_CHEST;
   public static final RegistryKey WOODLAND_MANSION_CHEST;
   public static final RegistryKey UNDERWATER_RUIN_SMALL_CHEST;
   public static final RegistryKey UNDERWATER_RUIN_BIG_CHEST;
   public static final RegistryKey BURIED_TREASURE_CHEST;
   public static final RegistryKey SHIPWRECK_MAP_CHEST;
   public static final RegistryKey SHIPWRECK_SUPPLY_CHEST;
   public static final RegistryKey SHIPWRECK_TREASURE_CHEST;
   public static final RegistryKey PILLAGER_OUTPOST_CHEST;
   public static final RegistryKey BASTION_TREASURE_CHEST;
   public static final RegistryKey BASTION_OTHER_CHEST;
   public static final RegistryKey BASTION_BRIDGE_CHEST;
   public static final RegistryKey BASTION_HOGLIN_STABLE_CHEST;
   public static final RegistryKey ANCIENT_CITY_CHEST;
   public static final RegistryKey ANCIENT_CITY_ICE_BOX_CHEST;
   public static final RegistryKey RUINED_PORTAL_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_COMMON_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_RARE_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_UNIQUE_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_OMINOUS_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_OMINOUS_RARE_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_SUPPLY_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_CORRIDOR_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_INTERSECTION_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_INTERSECTION_BARREL_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_ENTRANCE_CHEST;
   public static final RegistryKey TRIAL_CHAMBERS_CORRIDOR_DISPENSER;
   public static final RegistryKey TRIAL_CHAMBERS_CHAMBER_DISPENSER;
   public static final RegistryKey TRIAL_CHAMBERS_WATER_DISPENSER;
   public static final RegistryKey TRIAL_CHAMBERS_CORRIDOR_POT;
   public static final RegistryKey TRIAL_CHAMBER_EQUIPMENT;
   public static final RegistryKey TRIAL_CHAMBER_RANGED_EQUIPMENT;
   public static final RegistryKey TRIAL_CHAMBER_MELEE_EQUIPMENT;
   public static final Map SHEEP_DROPS_FROM_DYE_COLOR;
   public static final RegistryKey FISHING_GAMEPLAY;
   public static final RegistryKey FISHING_JUNK_GAMEPLAY;
   public static final RegistryKey FISHING_TREASURE_GAMEPLAY;
   public static final RegistryKey FISHING_FISH_GAMEPLAY;
   public static final RegistryKey CAT_MORNING_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_ARMORER_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_BUTCHER_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_CARTOGRAPHER_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_CLERIC_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_FARMER_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_FISHERMAN_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_FLETCHER_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_LEATHERWORKER_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_LIBRARIAN_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_MASON_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_SHEPHERD_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_TOOLSMITH_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_WEAPONSMITH_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_UNEMPLOYED_GIFT_GAMEPLAY;
   public static final RegistryKey HERO_OF_THE_VILLAGE_BABY_GIFT_GAMEPLAY;
   public static final RegistryKey SNIFFER_DIGGING_GAMEPLAY;
   public static final RegistryKey PANDA_SNEEZE_GAMEPLAY;
   public static final RegistryKey CHICKEN_LAY_GAMEPLAY;
   public static final RegistryKey ARMADILLO_SHED_GAMEPLAY;
   public static final RegistryKey PIGLIN_BARTERING_GAMEPLAY;
   public static final RegistryKey TRIAL_CHAMBER_KEY_SPAWNER;
   public static final RegistryKey TRIAL_CHAMBER_CONSUMABLES_SPAWNER;
   public static final RegistryKey OMINOUS_TRIAL_CHAMBER_KEY_SPAWNER;
   public static final RegistryKey OMINOUS_TRIAL_CHAMBER_CONSUMABLES_SPAWNER;
   public static final RegistryKey TRIAL_CHAMBER_ITEMS_TO_DROP_WHEN_OMINOUS_SPAWNER;
   public static final RegistryKey BOGGED_SHEARING;
   public static final RegistryKey MOOSHROOM_SHEARING;
   public static final RegistryKey MOOSHROOM_RED_SHEARING;
   public static final RegistryKey MOOSHROOM_BROWN_SHEARING;
   public static final RegistryKey SNOW_GOLEM_SHEARING;
   public static final RegistryKey SHEEP_SHEARING;
   public static final Map SHEEP_SHEARING_FROM_DYE_COLOR;
   public static final RegistryKey DESERT_WELL_ARCHAEOLOGY;
   public static final RegistryKey DESERT_PYRAMID_ARCHAEOLOGY;
   public static final RegistryKey TRAIL_RUINS_COMMON_ARCHAEOLOGY;
   public static final RegistryKey TRAIL_RUINS_RARE_ARCHAEOLOGY;
   public static final RegistryKey OCEAN_RUIN_WARM_ARCHAEOLOGY;
   public static final RegistryKey OCEAN_RUIN_COLD_ARCHAEOLOGY;

   private static Map registerAllDyeColors(String prefix) {
      return Util.mapEnum(DyeColor.class, (color) -> {
         return register(prefix + "/" + color.getId());
      });
   }

   private static RegistryKey register(String id) {
      return registerLootTable(RegistryKey.of(RegistryKeys.LOOT_TABLE, Identifier.ofVanilla(id)));
   }

   private static RegistryKey registerLootTable(RegistryKey key) {
      if (LOOT_TABLES.add(key)) {
         return key;
      } else {
         throw new IllegalArgumentException(String.valueOf(key.getValue()) + " is already a registered built-in loot table");
      }
   }

   public static Set getAll() {
      return LOOT_TABLES_READ_ONLY;
   }

   static {
      LOOT_TABLES_READ_ONLY = Collections.unmodifiableSet(LOOT_TABLES);
      SPAWN_BONUS_CHEST = register("chests/spawn_bonus_chest");
      END_CITY_TREASURE_CHEST = register("chests/end_city_treasure");
      SIMPLE_DUNGEON_CHEST = register("chests/simple_dungeon");
      VILLAGE_WEAPONSMITH_CHEST = register("chests/village/village_weaponsmith");
      VILLAGE_TOOLSMITH_CHEST = register("chests/village/village_toolsmith");
      VILLAGE_ARMORER_CHEST = register("chests/village/village_armorer");
      VILLAGE_CARTOGRAPHER_CHEST = register("chests/village/village_cartographer");
      VILLAGE_MASON_CHEST = register("chests/village/village_mason");
      VILLAGE_SHEPARD_CHEST = register("chests/village/village_shepherd");
      VILLAGE_BUTCHER_CHEST = register("chests/village/village_butcher");
      VILLAGE_FLETCHER_CHEST = register("chests/village/village_fletcher");
      VILLAGE_FISHER_CHEST = register("chests/village/village_fisher");
      VILLAGE_TANNERY_CHEST = register("chests/village/village_tannery");
      VILLAGE_TEMPLE_CHEST = register("chests/village/village_temple");
      VILLAGE_DESERT_HOUSE_CHEST = register("chests/village/village_desert_house");
      VILLAGE_PLAINS_CHEST = register("chests/village/village_plains_house");
      VILLAGE_TAIGA_HOUSE_CHEST = register("chests/village/village_taiga_house");
      VILLAGE_SNOWY_HOUSE_CHEST = register("chests/village/village_snowy_house");
      VILLAGE_SAVANNA_HOUSE_CHEST = register("chests/village/village_savanna_house");
      ABANDONED_MINESHAFT_CHEST = register("chests/abandoned_mineshaft");
      NETHER_BRIDGE_CHEST = register("chests/nether_bridge");
      STRONGHOLD_LIBRARY_CHEST = register("chests/stronghold_library");
      STRONGHOLD_CROSSING_CHEST = register("chests/stronghold_crossing");
      STRONGHOLD_CORRIDOR_CHEST = register("chests/stronghold_corridor");
      DESERT_PYRAMID_CHEST = register("chests/desert_pyramid");
      JUNGLE_TEMPLE_CHEST = register("chests/jungle_temple");
      JUNGLE_TEMPLE_DISPENSER_CHEST = register("chests/jungle_temple_dispenser");
      IGLOO_CHEST_CHEST = register("chests/igloo_chest");
      WOODLAND_MANSION_CHEST = register("chests/woodland_mansion");
      UNDERWATER_RUIN_SMALL_CHEST = register("chests/underwater_ruin_small");
      UNDERWATER_RUIN_BIG_CHEST = register("chests/underwater_ruin_big");
      BURIED_TREASURE_CHEST = register("chests/buried_treasure");
      SHIPWRECK_MAP_CHEST = register("chests/shipwreck_map");
      SHIPWRECK_SUPPLY_CHEST = register("chests/shipwreck_supply");
      SHIPWRECK_TREASURE_CHEST = register("chests/shipwreck_treasure");
      PILLAGER_OUTPOST_CHEST = register("chests/pillager_outpost");
      BASTION_TREASURE_CHEST = register("chests/bastion_treasure");
      BASTION_OTHER_CHEST = register("chests/bastion_other");
      BASTION_BRIDGE_CHEST = register("chests/bastion_bridge");
      BASTION_HOGLIN_STABLE_CHEST = register("chests/bastion_hoglin_stable");
      ANCIENT_CITY_CHEST = register("chests/ancient_city");
      ANCIENT_CITY_ICE_BOX_CHEST = register("chests/ancient_city_ice_box");
      RUINED_PORTAL_CHEST = register("chests/ruined_portal");
      TRIAL_CHAMBERS_REWARD_CHEST = register("chests/trial_chambers/reward");
      TRIAL_CHAMBERS_REWARD_COMMON_CHEST = register("chests/trial_chambers/reward_common");
      TRIAL_CHAMBERS_REWARD_RARE_CHEST = register("chests/trial_chambers/reward_rare");
      TRIAL_CHAMBERS_REWARD_UNIQUE_CHEST = register("chests/trial_chambers/reward_unique");
      TRIAL_CHAMBERS_REWARD_OMINOUS_CHEST = register("chests/trial_chambers/reward_ominous");
      TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON_CHEST = register("chests/trial_chambers/reward_ominous_common");
      TRIAL_CHAMBERS_REWARD_OMINOUS_RARE_CHEST = register("chests/trial_chambers/reward_ominous_rare");
      TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE_CHEST = register("chests/trial_chambers/reward_ominous_unique");
      TRIAL_CHAMBERS_SUPPLY_CHEST = register("chests/trial_chambers/supply");
      TRIAL_CHAMBERS_CORRIDOR_CHEST = register("chests/trial_chambers/corridor");
      TRIAL_CHAMBERS_INTERSECTION_CHEST = register("chests/trial_chambers/intersection");
      TRIAL_CHAMBERS_INTERSECTION_BARREL_CHEST = register("chests/trial_chambers/intersection_barrel");
      TRIAL_CHAMBERS_ENTRANCE_CHEST = register("chests/trial_chambers/entrance");
      TRIAL_CHAMBERS_CORRIDOR_DISPENSER = register("dispensers/trial_chambers/corridor");
      TRIAL_CHAMBERS_CHAMBER_DISPENSER = register("dispensers/trial_chambers/chamber");
      TRIAL_CHAMBERS_WATER_DISPENSER = register("dispensers/trial_chambers/water");
      TRIAL_CHAMBERS_CORRIDOR_POT = register("pots/trial_chambers/corridor");
      TRIAL_CHAMBER_EQUIPMENT = register("equipment/trial_chamber");
      TRIAL_CHAMBER_RANGED_EQUIPMENT = register("equipment/trial_chamber_ranged");
      TRIAL_CHAMBER_MELEE_EQUIPMENT = register("equipment/trial_chamber_melee");
      SHEEP_DROPS_FROM_DYE_COLOR = registerAllDyeColors("entities/sheep");
      FISHING_GAMEPLAY = register("gameplay/fishing");
      FISHING_JUNK_GAMEPLAY = register("gameplay/fishing/junk");
      FISHING_TREASURE_GAMEPLAY = register("gameplay/fishing/treasure");
      FISHING_FISH_GAMEPLAY = register("gameplay/fishing/fish");
      CAT_MORNING_GIFT_GAMEPLAY = register("gameplay/cat_morning_gift");
      HERO_OF_THE_VILLAGE_ARMORER_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/armorer_gift");
      HERO_OF_THE_VILLAGE_BUTCHER_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/butcher_gift");
      HERO_OF_THE_VILLAGE_CARTOGRAPHER_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/cartographer_gift");
      HERO_OF_THE_VILLAGE_CLERIC_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/cleric_gift");
      HERO_OF_THE_VILLAGE_FARMER_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/farmer_gift");
      HERO_OF_THE_VILLAGE_FISHERMAN_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/fisherman_gift");
      HERO_OF_THE_VILLAGE_FLETCHER_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/fletcher_gift");
      HERO_OF_THE_VILLAGE_LEATHERWORKER_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/leatherworker_gift");
      HERO_OF_THE_VILLAGE_LIBRARIAN_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/librarian_gift");
      HERO_OF_THE_VILLAGE_MASON_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/mason_gift");
      HERO_OF_THE_VILLAGE_SHEPHERD_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/shepherd_gift");
      HERO_OF_THE_VILLAGE_TOOLSMITH_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/toolsmith_gift");
      HERO_OF_THE_VILLAGE_WEAPONSMITH_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/weaponsmith_gift");
      HERO_OF_THE_VILLAGE_UNEMPLOYED_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/unemployed_gift");
      HERO_OF_THE_VILLAGE_BABY_GIFT_GAMEPLAY = register("gameplay/hero_of_the_village/baby_gift");
      SNIFFER_DIGGING_GAMEPLAY = register("gameplay/sniffer_digging");
      PANDA_SNEEZE_GAMEPLAY = register("gameplay/panda_sneeze");
      CHICKEN_LAY_GAMEPLAY = register("gameplay/chicken_lay");
      ARMADILLO_SHED_GAMEPLAY = register("gameplay/armadillo_shed");
      PIGLIN_BARTERING_GAMEPLAY = register("gameplay/piglin_bartering");
      TRIAL_CHAMBER_KEY_SPAWNER = register("spawners/trial_chamber/key");
      TRIAL_CHAMBER_CONSUMABLES_SPAWNER = register("spawners/trial_chamber/consumables");
      OMINOUS_TRIAL_CHAMBER_KEY_SPAWNER = register("spawners/ominous/trial_chamber/key");
      OMINOUS_TRIAL_CHAMBER_CONSUMABLES_SPAWNER = register("spawners/ominous/trial_chamber/consumables");
      TRIAL_CHAMBER_ITEMS_TO_DROP_WHEN_OMINOUS_SPAWNER = register("spawners/trial_chamber/items_to_drop_when_ominous");
      BOGGED_SHEARING = register("shearing/bogged");
      MOOSHROOM_SHEARING = register("shearing/mooshroom");
      MOOSHROOM_RED_SHEARING = register("shearing/mooshroom/red");
      MOOSHROOM_BROWN_SHEARING = register("shearing/mooshroom/brown");
      SNOW_GOLEM_SHEARING = register("shearing/snow_golem");
      SHEEP_SHEARING = register("shearing/sheep");
      SHEEP_SHEARING_FROM_DYE_COLOR = registerAllDyeColors("shearing/sheep");
      DESERT_WELL_ARCHAEOLOGY = register("archaeology/desert_well");
      DESERT_PYRAMID_ARCHAEOLOGY = register("archaeology/desert_pyramid");
      TRAIL_RUINS_COMMON_ARCHAEOLOGY = register("archaeology/trail_ruins_common");
      TRAIL_RUINS_RARE_ARCHAEOLOGY = register("archaeology/trail_ruins_rare");
      OCEAN_RUIN_WARM_ARCHAEOLOGY = register("archaeology/ocean_ruin_warm");
      OCEAN_RUIN_COLD_ARCHAEOLOGY = register("archaeology/ocean_ruin_cold");
   }
}
